force-app/main/default/objects/Alumno__c/Alumno__c.object-meta.xml
<CustomObject>
    <label>Alumno</label>
    <nameField>
        <label>Nombre Alumno</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alumnos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alumno__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>En mora</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Alumno__c/fields/N_mero_de_identidad__c.field-meta.xml
<CustomField>
    <fullName>N_mero_de_identidad__c</fullName>
    <label>Número de identidad</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asistencia__c/Asistencia__c.object-meta.xml
<CustomObject>
    <label>Asistencia</label>
    <nameField>
        <label>Asistencia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asistencia</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Asistencia__c/fields/Alumno__c.field-meta.xml
<CustomField>
    <fullName>Alumno__c</fullName>
    <label>Alumno</label>
    <referenceTo>Alumno__c</referenceTo>
    <relationshipLabel>Asistencia</relationshipLabel>
    <relationshipName>Asistencia</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/Fecha__c.field-meta.xml
<CustomField>
    <fullName>Fecha__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Fecha</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/HoraEntrada__c.field-meta.xml
<CustomField>
    <fullName>HoraEntrada__c</fullName>
    <defaultValue>TIMENOW()</defaultValue>
    <label>Hora de Entrada</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Asistencia__c/fields/MetodoRegistro__c.field-meta.xml
<CustomField>
    <fullName>MetodoRegistro__c</fullName>
    <label>MetodoRegistro</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Cédula</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>QR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChbAttendanceController.cls
public with sharing class ChbAttendanceController { 
    @AuraEnabled(cacheable=false)
    public static Alumno__c getAlumnosByCC(String CC) {
        if (String.isBlank(CC)) {
            return null;
        }
       List<Alumno__c> alumns= [ SELECT Id, Name, N_mero_de_identidad__c, Estado__c FROM Alumno__c WHERE N_mero_de_identidad__c = :CC LIMIT 1];
        if(alumns.isEmpty()){
            return null;
        }
        return alumns[0];
    }

    @AuraEnabled
    public static void markAttendance(Id alumnId){
        Asistencia__c Asist= new Asistencia__c(
                    Alumno__c = alumnId,
                    Name= 'Asistencia ' + Date.today(),
                    Fecha__c = Date.today(),
                    HoraEntrada__c = System.now().time(),
                    MetodoRegistro__c= 'Manual' );
       
    insert Asist;
    }
}